name: CI-CD Pipeline

on:
push:
branches:
- main

env:
IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/devops-app

jobs:
build-and-deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Login to DockerHub
    run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  - name: Build Docker Image
    run: docker build -t $IMAGE_NAME:${{ github.sha }} ./app

  - name: Push Docker Image
    run: docker push $IMAGE_NAME:${{ github.sha }}

  - name: Configure AWS
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      aws-region: ap-south-1

  - name: Update kubeconfig
    run: aws eks update-kubeconfig --region ap-south-1 --name neeraj-cluster

  - name: Deploy to Kubernetes
    run: |
      kubectl set image deployment/devops-deployment devops-container=$IMAGE_NAME:${{ github.sha }}
      kubectl apply -f k8s/
